sed -i -E "s/\\{ id: 'hyp-007'.*/\\{ id: 'hyp-007', title: 'Impact direct des sanctions économiques internationales', description: '...', statement: '...', status: 'FRAGILE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Économique' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-008'.*/\\{ id: 'hyp-008', title: 'Blocage logistique dû aux intempéries extrêmes', description: '...', statement: '...', status: 'SOUTENUE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Économique' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-009'.*/\\{ id: 'hyp-009', title: 'Spéculation massive des grossistes locaux', description: '...', statement: '...', status: 'PROPOSEE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Économique' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-010'.*/\\{ id: 'hyp-010', title: 'Cyberattaque d’origine étatique', description: '...', statement: '...', status: 'EN_EVALUATION', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Infra' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-011'.*/\\{ id: 'hyp-011', title: 'Sabotage physique par un groupe rebelle', description: '...', statement: '...', status: 'EN_EVALUATION', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Infra' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-012'.*/\\{ id: 'hyp-012', title: 'Défaillance technique critique non intentionnelle', description: '...', statement: '...', status: 'ECARTEE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Infra' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-013'.*/\\{ id: 'hyp-013', title: 'Exercice militaire naval inopiné', description: '...', statement: '...', status: 'SOUTENUE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Maritime' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-014'.*/\\{ id: 'hyp-014', title: 'Opération de contrebande à grande échelle', description: '...', statement: '...', status: 'CONTESTEE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Maritime' \\},/g" src/data/hypothesisDemoData.ts
sed -i -E "s/\\{ id: 'hyp-015'.*/\\{ id: 'hyp-015', title: 'Surveillance de navires de pêche illégale', description: '...', statement: '...', status: 'INSUFFISANTE', isDemo: true, provenance: 'SCENARIO_DEMO', analystId: 'Analyste Maritime' \\}/g" src/data/hypothesisDemoData.ts
